---
apiVersion: kubara.io/v1alpha1
kind: ServiceDefinition
metadata:
  name: metallb
  annotations:
    kubara.io/category: networking
spec:
  chartPath: metallb
  status: disabled
  clusterTypes: [hub, spoke]
  configSchema:
    type: object
    required: [publicLoadBalancerIPs, loadBalancerAddressPool]
    properties:
      publicLoadBalancerIPs:
        type: string
        description: Specifies a comma-separated list of IPs to be used for public DNS record targets https://kubernetes-sigs.github.io/external-dns/latest/docs/annotations/annotations/#external-dnsalphakubernetesiotarget
      loadBalancerAddressPool:
        type: array
        items:
          type: string
        description: MetalLB will allocate IPs from any configured address pool with free addresses. https://metallb.universe.tf/configuration/_advanced_ipaddresspool_configuration/
