---
apiVersion: v2
name: traefik
version: 2.3.1
description: This Chart deploys traefik.
dependencies:
  - name: traefik
    version: 41.2.0
    repository: oci://ghcr.io/traefik/helm
  - name: template-library
    repository: file://../template-library
    version: 0.2.1
